### ISSUE TITLE
Question about poses

### ISSUE THREAD

**Issue by sampepose** [BingyaoHuang/single-shot-pro-cam-calib#1]
Hi! Thanks for the code! I'm wondering about the checkerboard poses. Does it matter if the different poses are all co-planar? For instance, with an ultra-short throw projector, it would be very difficult to have a pose at an angle for depth. Thanks!

**Comment by sampepose** [comment]
Also, how many poses are "sufficient"?

**Comment by BingyaoHuang** [comment]
1. Co-planar poses are very likely to give poor calibrations. Different rotations around X and Y axes and offsets along Z axis can improve accuracy.

2. Three poses are sufficient. But more poses will improve the calibration accuracy.
