### ISSUE TITLE
Windows Executable - Stuck at "Extracting checkerboard corners from camera image..."

### ISSUE THREAD

**Issue by eldrickm** [BingyaoHuang/single-shot-pro-cam-calib#14]
Hi Bingyao,

I'm currently trying to use the windows executable and have captured a series of poses. Upon calibrating, I seem to be stuck at the above message with the progress bar not moving. I have tried manual segmentation masks and the captured images seem to look fine - both the plain and the projected grid images. I've attached a few below for verification.

What is the issue here?

I am on Windows 10 and am using the MATLAB R2021a runtime.

![image](https://user-images.githubusercontent.com/13305856/157120542-fc95d08b-6a43-45ea-a304-f7a775d5d705.png)
![image](https://user-images.githubusercontent.com/13305856/157120613-94111c0f-456f-4e22-91c0-8d8840ebf59e.png)

**Comment by BingyaoHuang** [comment]
Can I see the message in `log.txt` under your installation directory?

**Comment by eldrickm** [comment]
Hi Bingyao,

I solved this by using the exact number of checkerboard rows and columns as shown in your example images.

Thanks!
