### ISSUE TITLE
Obtain homography between camera and projector from calibration

### ISSUE THREAD

**Issue by RDKKKKKK** [BingyaoHuang/single-shot-pro-cam-calib#18]
Hi, thanks for the amazing software, the error is quite acceptable, really solved my trouble. But when I use the calibration result to calculate the homography between camera plane and projector plane, the outcome is not desired. I wonder is there an accurate way to obtain the homography from the calibration? 
Also I notice the nodePairs.yml in the output, I'm a little confused about the format in it.

**Comment by BingyaoHuang** [comment]
The homography may be inaccurate if your projector or camera has significant lens distortions.
`nodePairs.yml` stores the color grid nodes' coordinates in projector and camera image spaces.

**Comment by RDKKKKKK** [comment]
Thanks, i check the distortion but find it not significant. Maybe my method is not correct, currently i simply project some random 3D points onto camera and projector planes respectively, and use `cv2.findHomography` and `cv2.warpPerspective` to warp my camera image to projector view, may i ask is there a better way to do this?

**Comment by BingyaoHuang** [comment]
It may work if both images/2D points are undistorted, and the random points are correctly matched.
