### ISSUE TITLE
error use  cv.findHomography

### ISSUE THREAD

**Issue by fare129** [BingyaoHuang/single-shot-pro-cam-calib#19]
Hi Huang, now that I've run into this problem, can you please give some advice? I am using matlab2021a+mexopencv-3.4.1.
Detail：
错误使用 cv.findHomography
MEX �ļ���������ı�׼�쳣��
What() ��: OpenCV(3.4.1) D:\dev\opencv\modules\calib3d\src\fundam.cpp:372: error: (-5) The input arrays should be 2D or 3D point sets in function
cv::findHomography

��.

出错 Calibration.getNodesAndPrjCorners>findMatchAndWarp (第 83 行)
[Hcp, inliers] = cv.findHomography(camNodesUndistort, prjNodes, ...

出错 Calibration.getNodesAndPrjCorners (第 47 行)
        [prjCorners(:,:,i), nodePairs{i}] = findMatchAndWarp(imLightNames{i}, ...

出错 calibrateGUI (第 93 行)
[nodesCell, ~] = Calibration.getNodesAndPrjCorners(calibInfo, camParams, camCorners, verbose, useParallel);

出错 calibApp/CalibrateButtonPushed (第 868 行)
                calibrateGUI(app); % call calibration function
 
错误使用 matlab.ui.control.internal.controller.ComponentController/executeUserCallback (第 410 行)
计算 Button PrivateButtonPushedFcn 时出错。

**Comment by fare129** [comment]
These are the photos I took.
![colorGrid01](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/85798880/1502b7e1-92bf-41b0-9e89-3bdf6d5f44c2)
![colorGrid02](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/85798880/1194296c-e1f5-44d0-8188-0d831e461845)
![colorGrid03](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/85798880/250765c3-ee47-4796-9aa7-7398f6d49868)
![lightGrid01](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/85798880/af249a1a-68b0-4149-8ac6-344ddd88fdcd)
![lightGrid02](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/85798880/ca7cf738-fc97-4984-ba85-da713951b329)
![lightGrid03](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/85798880/9ada051d-ade2-4bf7-b1a7-e595edd6389a)

**Comment by fare129** [comment]
These are the photos I took.
![colorGrid01](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/85798880/473dcabf-b292-4021-80de-4237228d800c)
![colorGrid02](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/85798880/eda39274-663e-4aee-b532-ab704fe4a270)
![colorGrid03](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/85798880/5f08c3fa-6dfa-4205-80fe-af2d48836d6c)
![colorGrid04](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/85798880/ea92a547-fd04-4d32-a510-6da677fc73c7)
![colorGrid05](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/85798880/4aae5d17-11c5-49b6-a3c8-2a3c403cbb30)
![lightGrid01](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/85798880/b1b85bde-89ef-4281-a0b7-3fe025035b2f)
![lightGrid02](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/85798880/16a65cfb-b48b-4d08-b361-d55ee542f34f)
![lightGrid03](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/85798880/321e024c-4545-4a42-b26b-7d4dc216222a)
![lightGrid04](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/85798880/9536c0ca-8384-4aa6-8e3a-d8d88e497fb6)
![lightGrid05](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/85798880/dda82558-eaca-4a92-8ab3-440c12cd5f22)

**Comment by BingyaoHuang** [comment]
Can you check whether any of input to `cv.findHomography` is empty?

**Comment by fare129** [comment]
yes, it is empty, and when I use your data, the program works fine, but the data I collect myself reports an error. Can you tell me if it is because the background of the picture taken has an effect? A pure white background is needed is it?

**Comment by fare129** [comment]
Because when I reshot with a different background, there had a new problem:
索引中的冒号运算符的非有限端点或增量。

出错 ImgProc.segColorGrid (第 129 行)
        imBWCb(y-winSize:y+winSize,x-winSize:x+winSize) = 1;

出错 ImgProc.getMatchedNodes (第 28 行)
[imBWGrid, imColorGridMasked] = ImgProc.segColorGrid(whiteLight, colorGrid, camCorners, verbose);

出错 Calibration.getNodesAndPrjCorners>findMatchAndWarp (第 72 行)
[camNodes, prjNodes] = ImgProc.getMatchedNodes(imLightName, imColorName, camCorners, prjW, prjH, verbose);

出错 Calibration.getNodesAndPrjCorners (第 47 行)
        [prjCorners(:,:,i), nodePairs{i}] = findMatchAndWarp(imLightNames{i}, ...

出错 calibrateGUI (第 93 行)
[nodesCell, ~] = Calibration.getNodesAndPrjCorners(calibInfo, camParams, camCorners, verbose, useParallel);

出错 calibApp/CalibrateButtonPushed (第 868 行)
                calibrateGUI(app); % call calibration function
 
错误使用 matlab.ui.control.internal.controller.ComponentController/executeUserCallback (第 410 行)
计算 Button PrivateButtonPushedFcn 时出错。

**Comment by BingyaoHuang** [comment]
Maybe the board segmentation did not work well on your setup. You can set break point and debug the code, see whether the intermediate results look reasonable. You can tick `Verbose` option in the software to enter debug mode.

**Comment by fare129** [comment]
Yes, it will report an error on the segmentation part, does this look like it means that the background should be as whiteboard background as possible, as much as possible as in your case?
![1709543917768](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/85798880/c17526ab-ef91-4720-bb05-8ea088bc6a92)

**Comment by fare129** [comment]
Here's a photo captured from my second experiment.I don't think the interference should count for much anymore, but it's still a mistake in the segmentation.
![lightGrid01](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/85798880/092398cc-2590-416e-ab0f-05c6d20e0629)
![lightGrid01](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/85798880/351854fb-4ce3-49e6-b2f1-2df76382849e)

**Comment by fare129** [comment]
Here's a photo captured from my second experiment.I don't think the interference should count for much anymore, but it's still a mistake in the segmentation.
![colorGrid01](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/85798880/14d53eaa-d7f4-43a9-9d0e-cefd6b0b0f36)
![lightGrid01](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/85798880/0640fa3f-2918-4cc4-a21f-c51510e44840)

**Comment by BingyaoHuang** [comment]
> Yes, it will report an error on the segmentation part, does this look like it means that the background should be as whiteboard background as possible, as much as possible as in your case? ![1709543917768](https://private-user-images.githubusercontent.com/85798880/309698275-c17526ab-ef91-4720-bb05-8ea088bc6a92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDcwNzksIm5iZiI6MTcwOTU0Njc3OSwicGF0aCI6Ii84NTc5ODg4MC8zMDk2OTgyNzUtYzE3NTI2YWItZWY5MS00NzIwLWJiMDUtOGVhMDg4YmM2YTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDEwMDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0NjQ1MTRhMmU2OWQ2NTA5YmFlODRiYzIwYmJhZWU4MTI0MjQyODFmZDg5NzY1NmZmMTA1Mzg1NDFlY2Y4NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._8-HPMZmKhauSHNArIVw-A47fefLj7DfwbN8hRn7sUs)

The checkerboard region should be all black. You can check the segmentation results of my data, and compare it with yours.
