### ISSUE TITLE
The calibration program always stays on calibrating

### ISSUE THREAD

**Issue by yujiang0922** [BingyaoHuang/single-shot-pro-cam-calib#20]
when I tried with MATLAB Runtime way, the calibration program always stays on calibrating
![2](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/46923820/b5a7c06b-4cc3-4581-9f41-b4e77d184d33)

is there anything wrong?

**Comment by yujiang0922** [comment]
the error log:

Extracting checkerboard corners from camera image...
Calibrating camera using checkerboard corners...
Extracting and saving grid nodes and warped projector corners...
Starting parallel pool (parpool) using the 'local' profile ...
Connected to the parallel pool (number of workers: 8).
Extracting projector corners for image 1
Extracting projector corners for image 2
Extracting projector corners for image 3
错误使用 Calibration.getNodesAndPrjCorners>findMatchAndWarp (第 83 行)
MEX 文件 'C:\Users\jiang0922.yu\AppData\Local\Temp\jiang0922.yu\mcrCache9.10\ProCam0\Users\bingy\Documents\git\mexopencv\+cv\findHomography.mexw64' 无效: 找不到指定的模块。

出错 Calibration.getNodesAndPrjCorners (第 52 行)

出错 calibrateGUI (第 93 行)

出错 calibApp/CalibrateButtonPushed (第 848 行)

出错 appdesigner.internal.service.AppManagementService/tryCallback (第 377 行)

出错 matlab.apps.AppBase>@(source,event)tryCallback(appdesigner.internal.service.AppManagementService.instance(),app,callback,requiresEventData,event) (第 37 行)

错误使用 matlab.ui.control.internal.controller.ComponentController/executeUserCallback (第 410 行)
计算 Button PrivateButtonPushedFcn 时出错。

**Comment by BingyaoHuang** [comment]
Check whether `findHomography.mexw64` is under that directory.

**Comment by TIMESTICKING** [comment]
It's under that folder, then what to do. I'm using windows, and executing it from zip file

**Comment by BingyaoHuang** [comment]
I need more info

**Comment by TIMESTICKING** [comment]
It's the problem of "parallel", when I uncheck "parallel", the error gone

**Comment by BingyaoHuang** [comment]
Great, thank you for sharing this.
