### ISSUE TITLE
Here are some problem about "Objective function is returning undefined values at initial point. lsqnonlin cannot continue."

### ISSUE THREAD

**Issue by fare129** [BingyaoHuang/single-shot-pro-cam-calib#21]
Hello, thank you very much for the program, now I ran into a problem, is that I think I took the photo is very clear, why always encounter the error "Objective function is returning undefined values at initial point. lsqnonlin cannot continue“. And, according to the debug result, the error occurs during the process of fixing the point. How to solve this problem? Very much looking forward to your reply.
![1712116468643](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/85798880/a7150fb2-4e48-4e52-9a90-638fa678b177)
![1712116493211](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/85798880/c4db80ec-bd8c-47a7-92d4-ec443bac5253)
![1712116529132](https://github.com/BingyaoHuang/single-shot-pro-cam-calib/assets/85798880/c208d773-53a5-4597-be0c-e474629691c9)

**Comment by BingyaoHuang** [comment]
The color grid is not well decoded, the blue and red stripes are washed out. Try adjusting your projector and camera color settings.

**Comment by fare129** [comment]
Thanks for your respond, and my projector and camera both have a resolution of 1280 X 720.. Could it be a resolution issue, please?

**Comment by fare129** [comment]
The problem has been solved, firstly because the sports camera used, with wide angle shots, results in poor image quality. Secondly because the projector can't be too close to the calibration plate, otherwise the stripes are not clear from each other. After changing the camera and distancing the projector, the problem was solved. Thanks again.
