### ISSUE TITLE
Camera Light Image and Camera Grid Image are always the same

### ISSUE THREAD

**Issue by ENKRAN** [BingyaoHuang/single-shot-pro-cam-calib#24]
Hello,

currently i'm trying to capture images for different sets but 99% of the time, the Camera Light Image and the Camera Grid Image are the same and the grid is visible in both images. I tried many different things like adjusting settings in the camera control, rearranging the projector and camera, changing resoulutions, try to copy almost everything from your tutorial video and description but it still doesn't work like it did in your video on youtube. On very rare occations the capturing works for one set even though i didn't change any settings or lighting in the environment at all so i really can't tell what's causing this problem. An example screenshot is
attached too: 
![Screenshot (40)](https://github.com/user-attachments/assets/34c32ad9-c6dc-4ab6-892e-200b6027b805)

Help in some kind of way would be really appreciated. Thanks in advance.

**Comment by BingyaoHuang** [comment]
It's caused by the camera delay, and different cameras may have different delay times. 
Try increasing Exposure Time (s) to more than 2 seconds in the MATLAB code and let me know.

**Comment by ENKRAN** [comment]
Thanks for the fast reply! That worked, thank you.
