### ISSUE TITLE
Error until calibration step

### ISSUE THREAD

**Issue by guangyuhe** [BingyaoHuang/single-shot-pro-cam-calib#4]
Hi, 

Before the step of calibration, every thing is fine. But when I click the calibration, the error appears:

Undefined variable "cv" or class "cv.FileStorage".

Error in Calibration.loadCalibInfo (line 29)
calibInfo = cv.FileStorage(fullfile(calibPath, 'calib-info.yml'));

Error in calibrateGUI (line 33)
calibInfo = Calibration.loadCalibInfo(fullfile(dataRoot, dataName));
Undefined variable "cv" or class "cv.FileStorage".

Error in Calibration.loadCalibInfo (line 29)
calibInfo = cv.FileStorage(fullfile(calibPath, 'calib-info.yml'));

Error in calibrateGUI (line 33)
calibInfo = Calibration.loadCalibInfo(fullfile(dataRoot, dataName));
Undefined variable "cv" or class "cv.FileStorage".

Error in Calibration.loadCalibInfo (line 29)
calibInfo = cv.FileStorage(fullfile(calibPath, 'calib-info.yml'));

Error in calibrateGUI (line 33)
calibInfo = Calibration.loadCalibInfo(fullfile(dataRoot, dataName));
Undefined variable "cv" or class "cv.FileStorage".

Error in Calibration.loadCalibInfo (line 29)
calibInfo = cv.FileStorage(fullfile(calibPath, 'calib-info.yml'));

Error in calibrateGUI (line 33)
calibInfo = Calibration.loadCalibInfo(fullfile(dataRoot, dataName));

Please advise. Thanks

**Comment by guangyuhe** [comment]
The problem is fixed. Thanks anyway!!!

**Comment by BingyaoHuang** [comment]
Good to hear that. Is this due to mexopencv installation?

**Comment by guangyuhe** [comment]
Yes, it is. After the installation, I need to add the whole mexopencv folder to the path in Matlab.  Thanks

**Comment by LuShixong** [comment]
so i must install the  mexopencv?

**Comment by BingyaoHuang** [comment]
@LuShixong Yes.
