### ISSUE TITLE
error until  capture

### ISSUE THREAD

**Issue by xubin2015** [BingyaoHuang/single-shot-pro-cam-calib#7]
When I pressed the capture button, the screen was completely black,  after pressing the ESC showed the following error:

Warning: image too large to display on screen;It will be 67 percent
The object is invalid or deleted.
Error calibApp/CaptureButtonPushed (line 545)
ImLightGrid = app. CamPreviewImg. CData;
 
Error using the matlab.ui.control.internal.controller.Com ponentController/executeUserCallback (line 335)
Error calculating Button PrivateButtonPushedFcn.

Please advise. Thanks

**Comment by BingyaoHuang** [comment]
Here is a video [tutorial](https://www.youtube.com/watch?v=fnrVDOhcu7I&t=2s). Make sure the pattern is displayed on the projector screen.
