### ISSUE TITLE
Warning: Image is too large to display on screen; will show up at 67%.The object is invalid or has been deleted.

### ISSUE THREAD

**Issue by xubin2015** [BingyaoHuang/single-shot-pro-cam-calib#8]
Thank you very much!
When using  your system, I met a problem: when I push the capture button,the screen is dark and promted the following problem:
Warning: Image is too large to display on screen; will show up at 67%.The object is invalid or has been deleted.
Can you give me a email? I share the video with you.

**Comment by xubin2015** [comment]
I believe my pattern is right and I following your instruction in your video.
Best wishes to you.

**Comment by BingyaoHuang** [comment]
Sure. bingyao dot huang AT temple dot edu.

**Comment by xubin2015** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thank you very much.You can learn the problem I met by seeing the follwoing eight pictures. After I press the capture button,the screen are dark.Best wishes.
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                xu_bin
                            
                            
                                
                            
                    
                        
                            
                                    xu_bin@tju.edu.cn
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 9/11/2019 08:12，Bingyao Huang<notifications@github.com> wrote： 


Sure. bingyao dot huang AT temple dot edu.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
